//
//  SnapshotHelper.swift
//  OneBoxUITests
//
//  This file is auto-generated by fastlane snapshot.
//  To regenerate, run: fastlane snapshot init
//
//  NOTE: This is a placeholder. When you run `fastlane snapshot init`,
//  it will generate the full SnapshotHelper.swift with all required methods.
//

import XCTest

/// Snapshot helper class for fastlane screenshot automation
class Snapshot: NSObject {

    static var app: XCUIApplication?
    static var cacheDirectory: URL?
    static var screenshotsDirectory: URL? {
        return cacheDirectory
    }

    /// Initialize snapshot with the app instance
    class func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
        Snapshot.app = app

        // Set up cache directory for screenshots
        do {
            let cacheDir = try FileManager.default.url(
                for: .cachesDirectory,
                in: .userDomainMask,
                appropriateFor: nil,
                create: true
            )
            Snapshot.cacheDirectory = cacheDir
        } catch {
            print("Snapshot: Failed to create cache directory: \(error)")
        }

        // Add language setting from environment if available
        if let languageCode = ProcessInfo.processInfo.environment["SNAPSHOT_LANGUAGE"] {
            app.launchArguments.append("-AppleLanguages")
            app.launchArguments.append("(\(languageCode))")
        }

        // Add locale setting from environment if available
        if let localeCode = ProcessInfo.processInfo.environment["SNAPSHOT_LOCALE"] {
            app.launchArguments.append("-AppleLocale")
            app.launchArguments.append(localeCode)
        }
    }

    /// Take a screenshot with the given name
    class func snapshot(_ name: String, waitForLoadingIndicator: Bool = true) {
        guard let app = Snapshot.app else {
            print("Snapshot: App not set up. Call setupSnapshot() first.")
            return
        }

        if waitForLoadingIndicator {
            // Wait for any loading indicators to disappear
            let loadingIndicator = app.activityIndicators.firstMatch
            if loadingIndicator.exists {
                _ = loadingIndicator.waitForExistence(timeout: 30)
            }
        }

        // Small delay to ensure UI is stable
        sleep(1)

        // Take the screenshot
        let screenshot = app.screenshot()
        let attachment = XCTAttachment(screenshot: screenshot)
        attachment.name = name
        attachment.lifetime = .keepAlways

        // Save to disk if cache directory is available
        if let cacheDir = Snapshot.cacheDirectory {
            let fileURL = cacheDir.appendingPathComponent("\(name).png")
            do {
                try screenshot.pngRepresentation.write(to: fileURL)
                print("Snapshot: Saved \(name) to \(fileURL.path)")
            } catch {
                print("Snapshot: Failed to save \(name): \(error)")
            }
        }

        // Also add to Xcode test results
        #if DEBUG
        // In debug, we can access the test case context
        // This attachment will show up in Xcode test results
        #endif
    }

    /// Force a specific locale for screenshots
    class func setLanguage(_ language: String) {
        guard let app = Snapshot.app else { return }
        app.launchArguments.append("-AppleLanguages")
        app.launchArguments.append("(\(language))")
    }

    /// Force a specific locale for screenshots
    class func setLocale(_ locale: String) {
        guard let app = Snapshot.app else { return }
        app.launchArguments.append("-AppleLocale")
        app.launchArguments.append(locale)
    }
}
