# XcodeGen Configuration for OneBox
# Install XcodeGen: brew install xcodegen
# Run: xcodegen generate
# This will create OneBox.xcodeproj

name: OneBox
options:
  bundleIdPrefix: com.spuud
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en

settings:
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
  SWIFT_VERSION: "5.9"
  IPHONEOS_DEPLOYMENT_TARGET: "16.0"

targets:
  OneBox:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: OneBox
      - path: Modules
    resources:
      - OneBox/Assets.xcassets
      - OneBox/Preview Content
    info:
      path: OneBox/Info.plist
      properties:
        CFBundleDisplayName: Vault PDF
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSPhotoLibraryUsageDescription: "Vault PDF needs access to your photos to convert them to PDF"
        NSPhotoLibraryAddUsageDescription: "Vault PDF needs permission to save processed files"
        NSFaceIDUsageDescription: "Vault PDF uses Face ID to protect your documents and secure sensitive operations"
        UIBackgroundModes:
          - processing
        BGTaskSchedulerPermittedIdentifiers:
          - com.spuud.vaultpdf.process
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf
      INFOPLIST_FILE: OneBox/Info.plist
      CODE_SIGN_STYLE: Automatic
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      TARGETED_DEVICE_FAMILY: "1,2"
      ENABLE_PREVIEWS: true
      SWIFT_VERSION: "5.9"
      IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    dependencies:
      - target: CommonTypes
      - target: CorePDF
      - target: CoreImageKit
      - target: JobEngine
      - target: Payments
      - target: Ads
      - target: UIComponents
      - target: Privacy
    scheme:
      testTargets:
        - OneBoxTests

  # Framework Targets
  CommonTypes:
    type: framework
    platform: iOS
    sources:
      - Modules/CommonTypes
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.commontypes
      GENERATE_INFOPLIST_FILE: YES

  CorePDF:
    type: framework
    platform: iOS
    sources:
      - Modules/CorePDF
    dependencies:
      - target: CommonTypes
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.corepdf
      GENERATE_INFOPLIST_FILE: YES

  CoreImageKit:
    type: framework
    platform: iOS
    sources:
      - Modules/CoreImageKit
    dependencies:
      - target: CommonTypes
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.coreimagekit
      GENERATE_INFOPLIST_FILE: YES

  JobEngine:
    type: framework
    platform: iOS
    sources:
      - Modules/JobEngine
    dependencies:
      - target: CommonTypes
      - target: CorePDF
      - target: CoreImageKit
      - target: Privacy
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.jobengine
      GENERATE_INFOPLIST_FILE: YES

  Payments:
    type: framework
    platform: iOS
    sources:
      - Modules/Payments
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.payments
      GENERATE_INFOPLIST_FILE: YES

  Ads:
    type: framework
    platform: iOS
    sources:
      - Modules/Ads
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.ads
      GENERATE_INFOPLIST_FILE: YES

  UIComponents:
    type: framework
    platform: iOS
    sources:
      - Modules/UIComponents
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.uicomponents
      GENERATE_INFOPLIST_FILE: YES

  Privacy:
    type: framework
    platform: iOS
    sources:
      - Modules/Privacy
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.privacy
      GENERATE_INFOPLIST_FILE: YES

  # Test Targets
  OneBoxTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
        excludes:
          - "OneBoxUITests/**"
    dependencies:
      - target: OneBox
      - target: CorePDF
      - target: JobEngine
      - target: Payments
      - target: Privacy
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.tests
      GENERATE_INFOPLIST_FILE: YES

  # UI Test Target (separate for screenshots and UI testing)
  OneBoxUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: Tests/OneBoxUITests
    dependencies:
      - target: OneBox
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.spuud.vaultpdf.uitests
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: ""
      BUNDLE_LOADER: ""

schemes:
  OneBox:
    build:
      targets:
        OneBox: all
        OneBoxUITests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - OneBoxUITests
    archive:
      config: Release
